### PR TITLE
Updated header to properly support favicons and included complete example favicon

### PR DESCRIPTION
**Pull request by ottlinger**
Following https://favicon.io/favicon-converter/ I've added some more favicon URLs. One needs to put the following files into the static subfolder of one's hugo project:
* android-chrome-192x192.png
* android-chrome-512x512.png
* apple-touch-icon.png
* favicon-16x16.png
* favicon-32x32.png
* favicon.ico
* site.webmanifest

### CODE REVIEW

**Comment by ottlinger** [comment]
Should I update the documentation as well in order to properly inform users about how to include their own favicon file? Thanks

**Comment by ottlinger** [comment]
@opera7133 thanks for merging - I tried updating to the new version (that includes my favicon changes) locally and am unable to regenerate my hugo page. Do you experience the same behaviour?

```
Start building sites … 
hugo v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa+extended linux/amd64 BuildDate=2022-10-28T12:29:05Z VendorInfo=snap:0.105.0
ERROR 2022/11/05 12:37:47 render of "taxonomy" failed: "/home/foo/exampleHugo/themes/tella/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/list.html:5:8: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html: "<" in attribute name: "\r\n<link href='"
ERROR 2022/11/05 12:37:47 render of "home" failed: "/home/foo/exampleHugo/themes/tella/layouts/index.html:5:8": execute of template failed: template: index.html:5:8: executing "index.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html: "<" in attribute name: "\r\n<link href='"
ERROR 2022/11/05 12:37:47 render of "taxonomy" failed: "/home/foo/exampleHugo/themes/tella/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/list.html:5:8: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html: "<" in attribute name: "\r\n<link href='"
Error: Error building site: failed to render pages: render of "page" failed: "/home/foo/exampleHugo/themes/tella/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/single.html:5:8: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html: "<" in attribute name: "\r\n<link href='"
Built in 117 ms
```


I tried running npm install with no changes. Any clues what might go wrong?

**Comment by opera7133** [comment]
Now fixed. 66642d51f6e9fe4c277c4ee3503e34b155978a38

**Comment by ottlinger** [comment]
Ups - sry, copy&paste error! Thanks for the feedback

**Pull request merged**
